services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    # env_file:
    #   - .env

    container_name: ML-Services

    ports:
      - "7860:5100"

    volumes:
      - .:/app

    restart: unless-stopped

    networks:
      - ML-Services

networks:
  ML-Services:
